-- Neon compatibility patch for this fork.
-- This deployment uses FTS_SEARCH_PROVIDER=pg_like because Neon no longer allows pg_search.
-- Keep this migration as an intentional no-op so Drizzle records it and later migrations can continue.
